CREATE SEQUENCE "user_sequence"
  MINVALUE 0
  MAXVALUE 100500
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOCYCLE;

CREATE TABLE IF NOT EXISTS users (
  user_id   NUMBER(18, 10)  DEFAULT RANDOM_UUID() PRIMARY KEY,
  user_name VARCHAR2(100) DEFAULT NULL,
  first_name VARCHAR2(100) DEFAULT NULL,
  last_name VARCHAR2(100) DEFAULT NULL,
  email VARCHAR2(100) DEFAULT NULL,
  phone VARCHAR2(100) DEFAULT NULL
);