apiVersion: v1
kind: Service
metadata:
  name: eterna1ity-health-service
spec:
  selector:
    app: eterna1ity-health-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
