apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eternality-chart.fullname" . }}
  labels:
    {{- include "eternality-chart.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eternality-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eternality-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: eternality-secret
                  key: DATABASE_URI
            - name: HELLO_NAME
              valueFrom:
                configMapKeyRef:
                  name: eternality-config
                  key: HELLO_NAME