apiVersion: v2
name: eternality-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database